version: '3'

services:

  db:
    container_name: aedibus-db
    image: postgres
    restart: always
    hostname: db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: user
      POSTGRES_PASWORD: password
    ports:
      - 5432:5432
    networks:
      - aedibus-net
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  aedibus-api:
    container_name: aedibus-api
    image: escott07/aedibus-api:latest
    hostname: z3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
      Z3_GITHUBACCESSTOKEN: 7edf9968af97ac2a755ddc70fcacf8e1213d077d
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_MIGRATIONS: file:///app/migrations
    networks:
      - aedibus-net
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  aedibus-net:
    driver: bridge